# Generated by Django 3.2.17 on 2023-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Что вы хотите сообщить нам', verbose_name='текст обратной связи')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('email', models.EmailField(help_text='Ваша почта', max_length=150, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
            },
        ),
    ]
