# Generated by Django 3.2.17 on 2023-03-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('received', 'получено'), ('processing', 'в обработке'), ('answered', 'ответ дан')], default='received', max_length=16, verbose_name='статус обработки'),
        ),
    ]
