# Generated by Django 3.2.17 on 2023-03-12 20:48

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Прикрепите, если нужно, файлы', upload_to=feedback.models.get_file_media_path, verbose_name='файл')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback', verbose_name='обратная связь')),
            ],
        ),
    ]
