# Generated by Django 3.2.17 on 2023-03-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_separate_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': ('прикрепления',), 'verbose_name_plural': 'прикрепления'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='feedback',
            field=models.ForeignKey(help_text='Какому отзыву принадлежат прикрепления', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback', verbose_name='обратная связь'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.ForeignKey(help_text='Личная информация пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.contact', verbose_name='контакты'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('received', 'получено'), ('processing', 'в обработке'), ('answered', 'ответ дан')], default='received', help_text='Какой статус сейчас имеет отзыв', max_length=16, verbose_name='статус обработки'),
        ),
    ]
