[tool.black]
line-length = 79
exclude = ".*/migrations/"
[tool.isort]
profile = "google"
known_first_party = ["about","catalog","core","homepage","intensive", "feedback", "users"]
lines_after_imports = 2
skip_glob = "*/migrations"
[tool.autoflake]
in-place = true
remove-unused-variables = true
remove-all-unused-imports = true
[tool.djlint]
indent=2
profile="django"
use_gitignore = true
format_attribute_template_tags=true
