# Generated by Django 3.2.17 on 2023-02-20 17:02

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назовите объект', max_length=150, verbose_name='Имя')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован ли объект', verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Человекопонятный URL для объекта', max_length=200, unique=True, verbose_name='Строковый идентификатор')),
                ('weight', models.IntegerField(default=100, help_text='Насколько весома категория', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назовите объект', max_length=150, verbose_name='Имя')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован ли объект', verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Человекопонятный URL для объекта', max_length=200, unique=True, verbose_name='Строковый идентификатор')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назовите объект', max_length=150, verbose_name='Имя')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован ли объект', verbose_name='Опубликовано')),
                ('text', models.TextField(help_text='Введите описание объекта', validators=[catalog.validators.excellent_validator], verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Введите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(to='catalog.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
