# Generated by Django 3.2.17 on 2023-02-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catalog', '0002_normalization_name'), ('catalog', '0003_normalization_name_unique')]

    dependencies = [
        ('catalog', '0001_squashed_0002_text_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='normilized_name',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='normilized_name',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
    ]
