# Generated by Django 3.2.17 on 2023-02-20 21:09

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Введите описание объекта', validators=[catalog.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='Описание'),
        ),
    ]
