# Generated by Django 3.2.17 on 2023-02-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_squashed_0002_text_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='normilized_name',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='tag',
            name='normilized_name',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
    ]
