# Generated by Django 3.2.17 on 2023-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_normalization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='normilized_name',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normilized_name',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
    ]
