# Generated by Django 3.2.17 on 2023-02-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_normalization_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/', verbose_name='Фото')),
                ('item', models.OneToOneField(help_text='Какому товару принадлежит превью', on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='catalog.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Превью',
                'verbose_name_plural': 'Превьюшки',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/', verbose_name='Фото')),
                ('item', models.ForeignKey(help_text='Какому товару принадлежит фото', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотогалерея',
            },
        ),
    ]
