# Generated by Django 3.2.17 on 2023-03-05 10:13

import catalog.validators
import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_item_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'фотогалерея'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='preview',
            options={'verbose_name': 'превью', 'verbose_name_plural': 'превьюшки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Опубликован ли объект', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Назовите объект', max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Человекопонятный URL для объекта', max_length=200, unique=True, verbose_name='строковый идентификатор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=100, help_text='Насколько весома категория', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=core.models.get_item_media_path, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='item',
            field=models.ForeignKey(help_text='Какому товару принадлежит фото', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Введите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Опубликован ли объект', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Назовите объект', max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='catalog.Tag', verbose_name='тег'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Введите описание объекта', validators=[catalog.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='image',
            field=models.ImageField(upload_to=core.models.get_item_media_path, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='item',
            field=models.OneToOneField(help_text='Какому товару принадлежит превью', on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Опубликован ли объект', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Назовите объект', max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Человекопонятный URL для объекта', max_length=200, unique=True, verbose_name='строковый идентификатор'),
        ),
    ]
