# Generated by Django 3.2.17 on 2023-03-05 19:32

import core.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_dynamic_upload_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id', 'weight'), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('image',), 'verbose_name': 'фото', 'verbose_name_plural': 'фотогалерея'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name', 'id'), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='preview',
            options={'ordering': ('image',), 'verbose_name': 'превью', 'verbose_name_plural': 'превьюшки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('slug',), 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Сделайте это поле положительным, если хотите видеть товар на главной странице', verbose_name='на главной ли'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=core.models.get_item_media_path, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=core.models.get_item_media_path, verbose_name='фото'),
        ),
    ]
