# Generated by Django 3.2.17 on 2023-03-08 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_item_is_on_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
