# Generated by Django 3.2.17 on 2023-03-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_item_date_fields_auto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('weight', 'id'), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
