# Generated by Django 3.2.18 on 2023-03-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0010_category_ordering'),
        ('users', '0002_userproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(1, 'ненависть'), (2, 'неприязнь'), (3, 'нейтрально'), (4, 'обожание'), (5, 'любовь')], verbose_name='оценка товара')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_rating', to='users.userproxy')),
            ],
        ),
    ]
