# Generated by Django 3.2.17 on 2023-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemrating',
            options={'ordering': ('updated_at',)},
        ),
        migrations.AddField(
            model_name='itemrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
