# Generated by Django 3.2.17 on 2023-03-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userproxy'),
        ('catalog', '0010_category_ordering'),
        ('rating', '0002_rating_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemrating',
            options={'verbose_name': 'оценка', 'verbose_name_plural': 'оценки'},
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='item',
            field=models.ForeignKey(help_text='Товар для которого предназначен отзыва', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='score',
            field=models.SmallIntegerField(choices=[(1, 'ненависть'), (2, 'неприязнь'), (3, 'нейтрально'), (4, 'обожание'), (5, 'любовь')], help_text='Насколько вы оцениваете товар', verbose_name='оценка товара'),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='user',
            field=models.ForeignKey(help_text='Кто написал отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='item_rating', to='users.userproxy', verbose_name='пользователь'),
        ),
    ]
