name: ERD

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - '*/migrations/'
  
env:
  GRAPH_APPS: catalog,homepage,about


jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Generate ERD
      run: python manage.py graph_models -o erd.svg

    - name: Upload the ERD image
      uses: actions/upload-artifact@v3
      with:
        name: erd
        path: erd.svg